apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::159573017408:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-11M2YUHLOQ2ZA
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::159573017408:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-16T11:15:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1720"
  uid: 0dc5a646-e24e-477d-9146-ca29c444d125
